app:
  mode: "local"

logger:
  log_level: "info"
  log_output: ""

db: # host=localhost user=postgres password=rootroot dbname=GoChat port=5433 sslmode=disable
  host: "localhost"
  user: "postgres"
  password: "rootroot"
  port: 5433
  database: "GoChat"
  migration: true

api:
  address: "localhost"
  port: "7777"
